name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browser dependencies
        run: npx playwright install --with-deps

      - name: Build Observable site
        run: npm run build

      - name: Start local server for built site
        run: |
          npm install -g serve
          serve -s dist -l 4173 &
          echo $! > serve.pid
        shell: bash

      - name: Generate OG Image
        run: node scripts/capture-og.cjs
        env:
          NODE_ENV: production

      - name: Stop local server
        run: kill $(cat serve.pid)
        shell: bash
        if: always()

      - name: Copy OG Image to dist
        run: cp public/og.png dist/og.png

      - name: Upload OG Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: og-image
          path: dist/og.png

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_BUSH_04FD3F303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          api_location: ""
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_BUSH_04FD3F303 }}
          action: "close"
